### ISSUE TITLE
How to install compiled binaries to dictionary

### ISSUE THREAD

**Issue by kazunari03** [brijohn/gnuboy-ex#2]
I compiled these sources and generated binaries rightly.I'll trying to install exword devices(XD-N4800,Japanese model).I'm tried to install using libexword,But I couldn't find how to install this binaries.So how do I install those binaries to dictionary? I would be pleased if you could tell me.

**Comment by brijohn** [comment]
Once you build this you should have a directory called GNUBY under the build/ja directory. This needs to be copied over to the the following directory path $HOME/.local/share/exword/ja (This is the for Linux on windows or mac a different path is used). You should now be able to install this with exword using the following commands:
```
connect
dict reset <user> //This only needs to be done once
dict auth <user>
dict install GNUBY
exit
```

**Comment by kazunari03** [comment]
Thank you for the reply. When I compiled libexword 2.0-dev branch, it worked perfectly.
